### ISSUE TITLE
Update Coin List

### ISSUE THREAD

**Issue by cjdowner** [cjdowner/cryptocurrency-icons#1]

**Comment by CapitanRedBeard** [comment]
What's the ETA on the coin list update. Great work BTW!

**Comment by cjdowner** [comment]
@CapitanRedBeard Just updated. Thanks! :) https://github.com/cjdowner/cryptocurrency-icons/commit/f8a0efa2d9e5daa8bf9f235f3a299a71b65cbc6a

Will re-open another issue when I add more 🎉
