### ISSUE TITLE
Template?

### ISSUE THREAD

**Issue by razorsyntax** [cjdowner/cryptocurrency-icons#105]
If there's a template, I'd love to help contribute to this so we can get this list even longer than it is now.  These are my absolute favorite list of icons.

**Comment by cjdowner** [comment]
Oh I'll absolutely provide the template. I'll appreciate help now there are just too many coins.

I'll write up some documentation on the wiki to outline my process and best practises.

**Comment by cjdowner** [comment]
Done! - https://github.com/cjdowner/cryptocurrency-icons/wiki
