### ISSUE TITLE
Miss icon for BitcoinZ

### ISSUE THREAD

**Issue by imtase** [cjdowner/cryptocurrency-icons#11]
### BitcoinZ (BTCZ)  

* link to logo: https://bitcoinz.global/media/bitcoinz_btcz_logos.zip
* official website: https://bitcoinz.global

Optional info:  

* logo color (HEX): `#f8c24a`, `#f8e565`, `#ffa700` (main)  `#42abcc` (Z color)
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=2166510.0

**Comment by cjdowner** [comment]
Added - thanks for the assets and colours!
