### ISSUE TITLE
Add Request for Autonio (NIO)

### ISSUE THREAD

**Issue by cptkrvs** [cjdowner/cryptocurrency-icons#110]
Hello !
Thanks for your hard work and great library of coins :).

If you could please add Autonio (NIO) altcoin it would be very appreciated.
URL : https://auton.io
CMC : https://coinmarketcap.com/currencies/autonio/

I made all files you should need ready, please find it here 👍 : 
https://github.com/cptkrvs/autonio_assets/tree/master/icons_set

Thanks in advance !

**Comment by cjdowner** [comment]
Added, thank you for the files!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
