### ISSUE TITLE
Please, add coquicash icon

### ISSUE THREAD

**Issue by siulynot** [cjdowner/cryptocurrency-icons#111]
Hi, i work for the komodo platform team and would like to have the coquicash logo added to the icon pack. Here is the file, can tip for addition. Thanks!
![simbolo a](https://user-images.githubusercontent.com/225342/40119586-14397cc6-58eb-11e8-9fc1-bd049463c99f.png)

**Comment by lukechilds** [comment]
@siulynot can you host the SVG version and link that here too?

**Comment by siulynot** [comment]
Since github doesnt allow svg file upload, here i attach a .zip with the .svg version.
[coqui.svg.zip](https://github.com/cjdowner/cryptocurrency-icons/files/2009344/coqui.svg.zip)

**Comment by siulynot** [comment]
Since github doesnt allow svg file upload, here i attach a .zip with the .svg version.
[Uploading coqui.svg.zip…]()

**Comment by cjdowner** [comment]
Added - thanks for the images

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
