### ISSUE TITLE
Request: USD Icon

### ISSUE THREAD

**Issue by AYapejian** [cjdowner/cryptocurrency-icons#14]
Great project!  Not sure on your views on this but it would be great if there were some fiat icons to go along with the alt pairs, specifically USD for me but I'm sure others wouldn't mind EUR, JPY etc..  Was checking out the noun project and was going to make a simple one but I'm sure with the source files you could make a much better fit. 

Thanks again

**Comment by cjdowner** [comment]
What a great idea, thanks!

I have added USD, GBP, EUR, JPY, CNY, and RUB to start off with.

https://github.com/cjdowner/cryptocurrency-icons/commit/a7c59e1f54db772316c7f767ed8fed70ee481865

**Comment by AYapejian** [comment]
That's awesome, thanks!
