### ISSUE TITLE
Request: ICX and IOTA

### ISSUE THREAD

**Issue by sunabozu** [cjdowner/cryptocurrency-icons#15]
Would be great to see them in this pack.

[ICX](https://www.icon.foundation/en/)
[IOTA](https://blog.iota.org/)

**Comment by cjdowner** [comment]
Will close because these coins already exist.

https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/black/icx.png
https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/black/miota.png

**Comment by sunabozu** [comment]
I'm sorry, didn't see them. I had been looking in the `icons` folder.

**Comment by cjdowner** [comment]
That’s ok – all the tokens should be available in all styles and sizes!
