### ISSUE TITLE
Add BlockCoin

### ISSUE THREAD

**Issue by tetrisblockchain** [cjdowner/cryptocurrency-icons#16]
![logo_trans](https://user-images.githubusercontent.com/28805837/34465166-bdb24c38-ee56-11e7-8c7c-51843edf331d.png)
![blcn](https://user-images.githubusercontent.com/28805837/34465165-b5c70bc6-ee56-11e7-8583-caf14905a314.png)

**Comment by cjdowner** [comment]
What's the three letter code for BlockCoin?

**Comment by tetrisblockchain** [comment]
BLCN

**Comment by cjdowner** [comment]
Great. Added, thanks – https://github.com/cjdowner/cryptocurrency-icons/commit/7ceb159ab4f55697f8f304591b4c76ff45ec9437

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
