### ISSUE TITLE
Raiblocks (XRB) is wrong color.

### ISSUE THREAD

**Issue by Jake0303** [cjdowner/cryptocurrency-icons#18]
Title, correct color : https://themerkle.com/wp-content/uploads/raiblocks.jpg

**Comment by cjdowner** [comment]
This was a tough one due to the multi-colour logo and lack of apparent style guide.

I do think it would be more representative if it was using one of the blues, so I'll fix that in the next update

**Comment by cjdowner** [comment]
Just updated it – I've used a shade of blue from the logo, as well as updating the glyph so it isn't using a single, solid colour.

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
