### ISSUE TITLE
Digibyte logo updated

### ISSUE THREAD

**Issue by kyranjamie** [cjdowner/cryptocurrency-icons#2]
See thread on reddit:
https://www.reddit.com/r/Digibyte/comments/6uyqcr/refreshed_digibyte_logo_from_dgb_facebook/

They've (somewhat) updated the dgb logo.

**Comment by cjdowner** [comment]
I would have missed this – thanks for filing!

Big update coming soon. 🎉

**Comment by kyranjamie** [comment]
No worries, good job on the icons.

We wouldn't want one of them rotated 3º incorrectly 😂

**Comment by cjdowner** [comment]
@kyranjamie updated - cheers! https://github.com/cjdowner/cryptocurrency-icons/commit/f8a0efa2d9e5daa8bf9f235f3a299a71b65cbc6a
