### ISSUE TITLE
Request for Icon for EVX - Everex

### ISSUE THREAD

**Issue by HiGarethDavies** [cjdowner/cryptocurrency-icons#20]
https://www.everex.io/

https://coinmarketcap.com/currencies/everex/

**Comment by cjdowner** [comment]
Just added, thanks! 😄 

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.

**Comment by HiGarethDavies** [comment]
Thanks @cjdowner!
