### ISSUE TITLE
Request for Icon for START - Startcoin

### ISSUE THREAD

**Issue by dalaverd** [cjdowner/cryptocurrency-icons#21]
Website : https://startcoin.org/
Twitter : https://twitter.com/STARTCOINUK

**Comment by cjdowner** [comment]
Added in the latest commit, thanks!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
