### ISSUE TITLE
Request for Icon for NLC2 - No Limit Coin

### ISSUE THREAD

**Issue by row1** [cjdowner/cryptocurrency-icons#22]
https://nolimitcoin.org/#home

I haven't been able to find an SVG version of their coin icon, so this post might be a lost cause.

**Comment by cjdowner** [comment]
Not to worry, it was a relatively simple logo so I managed to draw it. Added, thanks!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
