### ISSUE TITLE
Request for Icon for POE - Po.et

### ISSUE THREAD

**Issue by SaswatB** [cjdowner/cryptocurrency-icons#23]
https://po.et/

https://coinmarketcap.com/currencies/poet/

**Comment by cjdowner** [comment]
Added, thanks!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.

**Comment by SaswatB** [comment]
Thank you!
