### ISSUE TITLE
NPM repository

### ISSUE THREAD

**Issue by Sharky1231** [cjdowner/cryptocurrency-icons#24]
Hi, 

would it be possible to put this project on NPM repository so we would not need to download the project every time there is an update but it would be rather automated?

Thanks,
Sharky

**Comment by dalaverd** [comment]
You can use the direct link such as 
`https://raw.githubusercontent.com/cjdowner/cryptocurrency-icons/master/32/icon/xlm.png`

**Comment by cjdowner** [comment]
I'll have a look into this

**Comment by Sicria** [comment]
If hot linking is not your thing, you can install it via ``npm install --save https://github.com/cjdowner/cryptocurrency-icons.git``.

Side note: Awesome project, thank you for maintaining this excellent collection of icons.

**Comment by Sharky1231** [comment]
@Sicria That helped nicely 👍
