### ISSUE TITLE
Request new icons

### ISSUE THREAD

**Issue by aburakovskiy** [cjdowner/cryptocurrency-icons#25]
Hi, thank you for a great job. It could be nice to add the most profitable mineable coins for current time that are missing
- [x] ZClassic [https://coinmarketcap.com/currencies/zclassic/](https://coinmarketcap.com/currencies/zclassic/)
- [x] GoByte [https://coinmarketcap.com/currencies/gobyte/](https://coinmarketcap.com/currencies/gobyte/)
- [x] Pascal Lite [https://coinmarketcap.com/currencies/pascal-lite/](https://coinmarketcap.com/currencies/pascal-lite/)
- [x] VIVO [https://coinmarketcap.com/currencies/vivo/](https://coinmarketcap.com/currencies/vivo/)
- [x] LBRY Credits [https://coinmarketcap.com/currencies/library-credit/](https://coinmarketcap.com/currencies/library-credit/)
- [x] TrezarCoin [https://coinmarketcap.com/currencies/trezarcoin/](https://coinmarketcap.com/currencies/trezarcoin/)
- [x] Hush [https://coinmarketcap.com/currencies/hush/](https://coinmarketcap.com/currencies/hush/)

**Comment by cjdowner** [comment]
Added all the above. Thanks! https://github.com/cjdowner/cryptocurrency-icons/commit/9fd054759095db9bc4dee2b4c96ae92bc75894f6

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
