### ISSUE TITLE
Update Bitcoin Cash (BCH) Icon Color from Orange to Green

### ISSUE THREAD

**Issue by seth-reeser** [cjdowner/cryptocurrency-icons#26]
See release from [Exodus](https://www.exodus.io/releases/):

The Bitcoin Cash logo has been changed to green from orange. This matches design choices made at Coinbase and seems to help users from mistaking Bitcoin Cash from Bitcoin when sending and receiving.

**Comment by cjdowner** [comment]
Great shout. Fixed https://github.com/cjdowner/cryptocurrency-icons/commit/9fd054759095db9bc4dee2b4c96ae92bc75894f6

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.

**Comment by seth-reeser** [comment]
Thanks, @cjdowner!
