### ISSUE TITLE
Include DeepBrainChain Icon please

### ISSUE THREAD

**Issue by gelsas** [cjdowner/cryptocurrency-icons#27]
Hello, could you also include a deepbrain chain icon please

**Comment by cjdowner** [comment]
Added – https://github.com/cjdowner/cryptocurrency-icons/commit/9fd054759095db9bc4dee2b4c96ae92bc75894f6

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
