### ISSUE TITLE
 Request for Icon for LINK - ChainLink

### ISSUE THREAD

**Issue by SaswatB** [cjdowner/cryptocurrency-icons#28]
https://coinmarketcap.com/currencies/chainlink/

https://www.smartcontract.com/

**Comment by cjdowner** [comment]
Added – https://github.com/cjdowner/cryptocurrency-icons/commit/9fd054759095db9bc4dee2b4c96ae92bc75894f6

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
