### ISSUE TITLE
Request for Icon for XDN - DigitalNote

### ISSUE THREAD

**Issue by dalaverd** [cjdowner/cryptocurrency-icons#29]
Website : http://digitalnote.org/
CoinMarketCap : https://coinmarketcap.com/currencies/digitalnote/

**Comment by cjdowner** [comment]
Added – https://github.com/cjdowner/cryptocurrency-icons/commit/9fd054759095db9bc4dee2b4c96ae92bc75894f6

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.

**Comment by dalaverd** [comment]
Thank you very much!
