### ISSUE TITLE
Consider using currency codes

### ISSUE THREAD

**Issue by ianpaschal** [cjdowner/cryptocurrency-icons#3]
Very nice icon set. I was trying to implement it in a project and I realized there's some strange naming conventions. For example, Ethereum is called "Ether" and Ethereum Classic is called "ETH-Classic".

I would propose a renaming to use currency symbols like BTC, LTC, ETH, ETC, etc. to avoid confusion. It would also make it easy in programing situations where you'd like to simply swap the value's code, a string such as `"BTC"` or `"ETH"` for the image of it... voila: `"../assets/icons/"+code+".png"`.

**Comment by cjdowner** [comment]
That's a great idea. Let me make sure those are consistent in the next update 👍

**Comment by ianpaschal** [comment]
Cool. I can also do it for myself and submit a PR but I wanted to see your reaction to the idea before I spend time on it.

**Comment by cjdowner** [comment]
That's kind - I appreciate the offer. I batch renamed those in the source file and am working on an update including new icons and updates as we speak :)

**Comment by cjdowner** [comment]
https://github.com/cjdowner/cryptocurrency-icons/commit/f8a0efa2d9e5daa8bf9f235f3a299a71b65cbc6a

**Comment by TAiS46** [comment]
Some names are still wrong. `miota` should be `iot` also there are whitespaces in the names `cryptocurrency-icons/svg/icon/ada .svg` (as example)

**Comment by TAiS46** [comment]
@cjdowner can we have an update on this?

**Comment by ianpaschal** [comment]
I've made a fork of the repo. Working on renaming stuff correctly. Two proposed changes I'd maybe roll into one, and I'm posting here to get a second or third opinion on are:

- Use upper case codes. In most contexts I'm storing codes as strings and avoid having to transform them if the string is just `"USD"` or `"BTC"` or `"ETH"` or whatever. The file would be `"ETH.png"`
- Keep variants stored by currency. I realize this is just personal opinion but having different sizes of the same icon (or different formats) reminds me of keeping icon assets together in a folder like `myIcon_32x32.png` and `myIcon_32x32@2x.png`. Therefore I'd propose a structure with paths like `/[CODE]/[STYLE]_[SIZE].[EXT]`. So for example: `/BTC/black_32x32@2x.png` or `/ETH/icon.svg`

These two suggestions aren't mutually inclusive so I could do one and then the other but I don't want to sit down and churn through this until I know exactly what I'm going for.

**Comment by cjdowner** [comment]
@TAiS46 the currency codes are somewhat subjective. I sourced them from [Coinmarketcap](https://coinmarketcap.com/currencies/iota/). I know Kraken for example do their own thing.

@ianpaschal thanks for the fork - you're very welcome to. I opted for lowercase names as that tends to be more of a standard in my experience, as with how I've delivered them, but I think personal preference comes into it too.

I will update fixing the whitespaces

**Comment by ianpaschal** [comment]
Ugh. Kraken. As if their platform wasn't broken enough already, I do a "Heh, whaaat?" every time I see "XBT" instead of "BTC".

I'm pretty busy this weekend so if you do it now you'll probably beat me to it with an update, although in this case I'll go for my different organizational structure so that it's out there if anyone prefers it.

Thanks for putting this resource together. I think it's the most complete crypto icon set out there.

**Comment by cjdowner** [comment]
@ianpaschal Haha. Sure thing, I'll cc you on my commit.

Let me know when you get the opportunity to fork it, and I'll link to it on the readme as I'm sure people would like the option 👍 

You're welcome – I don't always have the time, but do have more coins in the pipeline

**Comment by kdar** [comment]
Not to be pedantic, but I don't think naming the files by their currency code is a good idea. Not only do some cryptocurrency codes clash (BTG for Bitcoin Gold and Bitgem), but also some cryptocurrency codes clash with fiat currencies (ALL for the fiat Albanian lek and the cryptocurrency Allion). Not to mention different exchanges use different currency codes.

I think it makes more unambiguous sense to name the icons by their actual currency name.
