### ISSUE TITLE
Some missing Icons

### ISSUE THREAD

**Issue by GMarzinotto** [cjdowner/cryptocurrency-icons#30]
Hello thank you very much for your contribution,

I found the following missing coins for the Poloniex Exchange:
- RIC  | Riecoin
- XPM | Primecoin
- VIA | Viacoin
- FLO | Florincoin
- BLK | BlackCoin
- BELA | Bela
- BURST | Burst
- GRC | Gridcoin Research
- HUC | Huntercoin
- NEOS | Neoscoin
- NXC | Nexium
- OMNI | Omni
- PASC | PascalCoin
- PINK | Pinkcoin
- RADS | Radium
- SBD | Steem Dollars
- XBC | BitcoinPlus
- CLAM | Clams
- SYS | Syscoin
- VRC | VeriCoin
- FLDC | FoldingCoin
- XVC | Vcash
- EXP | Expanse
- LBC | LBRY Credits
- BCY | BitCrystals

I'm available to help to complete them!

**Comment by cjdowner** [comment]
OK, that will keep me busy for a while. I know off the top of my head LBRY Credits, PascalCoin were added in the last update.

I can take care of these, but if you have SVG logos of any of those coins that will save me a lot of time. Thanks!

**Comment by GMarzinotto** [comment]
I have found this site that has the svg of some of the above mentioned
https://labs.allienworks.net/icons/cryptocoins/

Pinkcoin
Syscoin
Primecoin
among others,

They are in a github repository as well

**Comment by cjdowner** [comment]
Awesome, thanks!

**Comment by cjdowner** [comment]
Just added a bunch of these - https://github.com/cjdowner/cryptocurrency-icons/commit/03d28f33567a5131e1310c30a3bcc9bfd43f8e9b

The only ones missing are Syscoin (unable to export correctly SVG versions of its logo) and BitCrystals as I don't have a suitable version of the logo for SVG.

I said in the commit I added `BitCrystals`, but I meant to say `Expanse`

**Comment by taulen** [comment]
I will also request
PIRL
ELLAISM

And thank you for the good job you're doing ! =)

**Comment by mfappsandweb** [comment]
Magicoin (XMG) also missing from icons

**Comment by cjdowner** [comment]
All added. Going to close this. Thanks! https://github.com/cjdowner/cryptocurrency-icons/commit/df853affd2781573cdd8b3ed38256a84bfd5a39f

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
