### ISSUE TITLE
Request for Icon for RISE

### ISSUE THREAD

**Issue by dalaverd** [cjdowner/cryptocurrency-icons#32]
Website : https://rise.vision/
Coinmarketcap : https://coinmarketcap.com/currencies/rise/

**Comment by cjdowner** [comment]
Added, thanks! https://github.com/cjdowner/cryptocurrency-icons/commit/df853affd2781573cdd8b3ed38256a84bfd5a39f

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
