### ISSUE TITLE
Various Alt Coins Missing form the CMC top 100

### ISSUE THREAD

**Issue by altShiftDev** [cjdowner/cryptocurrency-icons#33]
First of all, thank you for all your work, this project is amazing and very helpful. Secondly I went down the CMC (https://coinmarketcap.com/) top 100 coins and these are the ones I found were missing from your project:

*Format: {{ CoinName }} | {{ Symbol }}*

1. Maker | MKR
2. MediBloc | MED
3. Experience Points | XP
4. Syscoin | SYS
5. PACcoin | PAC
6. Cindicator | CND
7. Nebulas | NAS

**Comment by deval93** [comment]
Thank you for your feedback. We will fix this in next update.

**Comment by cjdowner** [comment]
Added. Thanks for the kind words! https://github.com/cjdowner/cryptocurrency-icons/commit/df853affd2781573cdd8b3ed38256a84bfd5a39f

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
