### ISSUE TITLE
Nodez

### ISSUE THREAD

**Issue by Serpent6877** [cjdowner/cryptocurrency-icons#34]
http://www.nodezcrypto.io/

Launching 01/21/18

**Comment by Serpent6877** [comment]
P.S. Sent you some LTC.

**Comment by cjdowner** [comment]
Added - https://github.com/cjdowner/cryptocurrency-icons/commit/1aeb44f526e66e33cb07da2d6d3df520b4a2d688

Thank you, that's very much appreciated! 😄
