### ISSUE TITLE
XMY and OX missing

### ISSUE THREAD

**Issue by dcaliri** [cjdowner/cryptocurrency-icons#35]
As per what it says in the readme, this are the ones that I use that are missing in the repo.

XMY > https://coinmarketcap.com/currencies/myriad/
OX > https://coinmarketcap.com/currencies/ox-fina/

**Comment by cjdowner** [comment]
Both coins are now added. Thanks! https://github.com/cjdowner/cryptocurrency-icons/commit/62d1b64467bc27c882333f4578346bffddde6df2

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
