### ISSUE TITLE
RPX, QLC, TNC

### ISSUE THREAD

**Issue by RobertLemmens** [cjdowner/cryptocurrency-icons#36]
First of all; great pack.

Some missing, new coins that are new on the NEO platform are RPX (red pulse), QLC(qlink) and TNC(Trinity).

**Comment by bartcoelus** [comment]
Hi. I asked our designer to prepare some icons for QLC. I attach his work here. Please lemme know if you need some additional things.  coebar / Qlink
[Qlink_CoinIcon.zip](https://github.com/cjdowner/cryptocurrency-icons/files/1665918/Qlink_CoinIcon.zip)

**Comment by cjdowner** [comment]
All added - thanks! https://github.com/cjdowner/cryptocurrency-icons/commit/62d1b64467bc27c882333f4578346bffddde6df2

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.

**Comment by RobertLemmens** [comment]
@bartcoelus @cjdowner Thanks, looks great!
