### ISSUE TITLE
OST (Simple Token) missing

### ISSUE THREAD

**Issue by xsaliniere** [cjdowner/cryptocurrency-icons#37]
Hey man, thanks for this very helpful pack.
Can you please add the OST token icon please ?

Thanks :)

**Comment by cjdowner** [comment]
Thanks! :) It's now added https://github.com/cjdowner/cryptocurrency-icons/commit/62d1b64467bc27c882333f4578346bffddde6df2

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
