### ISSUE TITLE
svg wrong size?

### ISSUE THREAD

**Issue by TAiS46** [cjdowner/cryptocurrency-icons#4]
We use the svg in size 32x32 but the inner icon is 30x30. I am not sure if this is because of a shadow or something. This will result to the following:

<img width="295" alt="screen shot 2017-11-26 at 12 06 15" src="https://user-images.githubusercontent.com/1446685/33237307-569e672c-d2a2-11e7-95d4-32778b12edfb.png">
<img width="277" alt="screen shot 2017-11-26 at 12 06 10" src="https://user-images.githubusercontent.com/1446685/33237308-56d57d52-d2a2-11e7-9727-686d4326bd4d.png">
<img width="302" alt="screen shot 2017-11-26 at 12 06 05" src="https://user-images.githubusercontent.com/1446685/33237309-570b18ea-d2a2-11e7-8ad8-449cf83bcdb9.png">

**Comment by cjdowner** [comment]
To confirm, this is the SVG variant from the `icon` folder? It looks like it is, however there is no gradient or shadow.

If so - that's expected. The icon shape has been drawn at that size to include the shadow within the dimension's bounds.

<img width="580" alt="screen shot 2017-11-26 at 15 43 39" src="https://user-images.githubusercontent.com/2099705/33241678-c0413e5c-d2c0-11e7-80f4-2e9bdc0eb793.png">

I would suggest using the variant from the `color` folder to see your expected results.
