### ISSUE TITLE
WABI Missing

### ISSUE THREAD

**Issue by mattharris191** [cjdowner/cryptocurrency-icons#43]
The icons look great!

**Comment by cjdowner** [comment]
Added - https://github.com/cjdowner/cryptocurrency-icons/commit/1f918b8910627f7d13ac122f641808750b122c30

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
