### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kdar** [cjdowner/cryptocurrency-icons#5]
Would be nice to know what this is licensed under.

**Comment by MarcelJurtz** [comment]
I second this. As long as there is no license, it's not actually open source. Thanks!

**Comment by cjdowner** [comment]
This is under the cc0 license, so you're free to use it however you wish. I will include this in the readme with the next update. 👍

**Comment by MarcelJurtz** [comment]
Alright, but it should be explicitly specified. Thanks! And thank you for your work, looks really great!

**Comment by cjdowner** [comment]
@MarcelJurtz thank you! Updated the project, and readme.
