### ISSUE TITLE
Naming convention - nano

### ISSUE THREAD

**Issue by mmagerl** [cjdowner/cryptocurrency-icons#50]
I have noticed that the icons are named by the currency code. However, after the RaiBlocks rebranding to Nano, the new icon is called nano, while the currency code stayed the same (XRB), according to coinmarketcap - https://coinmarketcap.com/currencies/raiblocks/.

**Comment by cjdowner** [comment]
Good catch - fixed thanks!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
