### ISSUE TITLE
IOP (Internet of People)

### ISSUE THREAD

**Issue by spasma** [cjdowner/cryptocurrency-icons#51]
Great icon set, cjdowner!

I am missing the IOP-icon in your set. it's quite a complex one to get in icon form i guess;
example: http://files.coinmarketcap.com.s3-website-us-east-1.amazonaws.com/static/img/coins/200x200/internet-of-people.png

**Comment by cjdowner** [comment]
Ugh. Created a simplified version of this that ought to work at small sizes.

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
