### ISSUE TITLE
Request icon: Blocktix (TIX), Feathercoin (FTC)

### ISSUE THREAD

**Issue by ZerglingGo** [cjdowner/cryptocurrency-icons#52]
Hello, i found missing icons and request to add it.

- [x] Blocktix (TIX) https://coinmarketcap.com/currencies/blocktix/
- [x] Fethercoin (FTC) https://coinmarketcap.com/currencies/feathercoin/

Thank you for your nice project :)

**Comment by cjdowner** [comment]
Done, and done. Thanks!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
