### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by deanlogic** [cjdowner/cryptocurrency-icons#54]
Some tokens missing from the current Top 100 list. 

Revian Token (R)
http://revain.org/

Zilliqa (ZIL)
https://www.zilliqa.com/

Ecoin (ECN)
https://www.e-coin.com/

SingularityNet (AGI)
https://singularitynet.io/

Polymath (POLY)
https://www.polymath.network/

I'm using your icons on my ["To The Moon!" Coin Calculator](http://demo.deanlogic.com/coins/). I'll definitely tip you some crypto when I get the chance. I don't have much BTC.  I'm also adding some text to show where I got the icons from on the page.

Thanks.

**Comment by cjdowner** [comment]
All added. https://github.com/cjdowner/cryptocurrency-icons/commit/f1fcfaec06c52f38cf6004c0557c306357ce9cbd Thanks for sharing your project, always love seeing the icons in use.

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
