### ISSUE TITLE
Icon for Tronix (TRX)

### ISSUE THREAD

**Issue by ElephantFishCrab** [cjdowner/cryptocurrency-icons#55]
Pretty much what the title says. I wish there could be an icon for TRX. Currently using an [SVG](https://worldvectorlogo.com/logo/tron) replacement but the scaling is all whack.

**Comment by renekorss** [comment]
But there is: https://github.com/cjdowner/cryptocurrency-icons/blob/master/svg/color/trx.svg

**Comment by ElephantFishCrab** [comment]
Ah, sorry. I was mistaking this repository for the 'cryptocoins-icons' icon font.. My bad
