### ISSUE TITLE
add eboost

### ISSUE THREAD

**Issue by nbawane** [cjdowner/cryptocurrency-icons#56]
please add eboost as well

**Comment by cjdowner** [comment]
Added. https://github.com/cjdowner/cryptocurrency-icons/commit/f1fcfaec06c52f38cf6004c0557c306357ce9cbd Thanks!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
