### ISSUE TITLE
A couple icons I'm missing at the moment

### ISSUE THREAD

**Issue by PSinke** [cjdowner/cryptocurrency-icons#57]
Thanks for creating this. I'm working on a crypto portfolio site, and am currently missing the following icons  (pretty much all of these coins are traded on binance):

- [ ] AMB
- [ ] APPC
- [ ] ARN
- [ ] BCD
- [ ] BCPT
- [ ] CDT
- [ ] DLT
- [ ] DNT
- [ ] ENJ
- [ ] FUEL
- [ ] GTO
- [x] IOTA
- [ ] LEND
- [ ] LUN
- [ ] MTH
- [x] NANO
- [ ] OAX
- [ ] SNM
- [ ] TNT
- [x] TRIG
- [ ] VIBE
- [ ] YOYO

Would be awesome to see these included in the project. I'll make sure to show you in the credits. If the site actually starts to make any money, you'll be the first to receive a nice tip.

**Comment by ZerglingGo** [comment]
IOTA already exists [miota.png](https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/icon/miota.png)

**Comment by imnotadeveloper** [comment]
@cjdownerhere, to help you in your research, here are the officials logos in vectors for the missing logo in the top 100 cryptocurrencies: 
Nano (NANO): https://nano.org/assets/img/logo.svg
Revain (R): https://static.cryptorival.com/imgs/coins/R.svg
Polymath (POLY) : https://global-uploads.webflow.com/5a46fad33472ef00014b540a/5a46fad33472ef00014b5433_a.svg

**Comment by cjdowner** [comment]
@imnotadeveloper - oh that's great. I appreciate it. Looking to find some time to update repository and close the open issues this weekend.

**Comment by alexmustin** [comment]
On CoinMarketCap there are over 2500 currencies. I was hoping this repo would have them all so I could use it for a WordPress plugin I'm developing.

So I created a PHP script that manually downloads them in blocks of 50 images at a time.

They are 32x32 .pngs but have pretty low res, unfortunately. But it will work for what I need.

Let me know if you want me to post a link to all the files...

**Comment by cjdowner** [comment]
They've all been added in this commit. Some were already there previously. https://github.com/cjdowner/cryptocurrency-icons/commit/f1fcfaec06c52f38cf6004c0557c306357ce9cbd

@alexmustin – Sorry, I just do this in my spare time. I don't think I'll ever do them all. I usually need to go to the protocol's site to grab the logos usually as I find CoinMarketCap to be too low-res to be that useful, really.

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
