### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by TheRealBomber** [cjdowner/cryptocurrency-icons#59]
Hey cjdowner,

thanks for putting together the list of icons! Appreciate your work.
A few icons I am missing are the following:
Elix - https://elixirtoken.io/
Bounty0x - https://bounty0x.io/
Blockport - https://blockport.io/

Also I'm not quite sure if the icon for Chainlink (LINK) is correct though I can't really tell what their real logo is. There is a logo on their subreddit: 
https://www.reddit.com/r/LINKTrader/
https://www.smartcontract.com/link

Thanks in advance!

**Comment by cjdowner** [comment]
Added. https://github.com/cjdowner/cryptocurrency-icons/commit/f1fcfaec06c52f38cf6004c0557c306357ce9cbd

I needed to take some artistic liberties with the LINK icon. Their logo isn't that suitable for the style I'm using, so I took the padlock from it.


---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
