### ISSUE TITLE
EXMO, QIWI, MUSICOIN, SBERBANK, SALT

### ISSUE THREAD

**Issue by SteeinGit** [cjdowner/cryptocurrency-icons#6]
Please add them: EXMO, QIWI, MUSICOIN, SBERBANK, SALT (webfont)

---

### Coin name (`EXMO`)

* link to logo: http://content.screencast.com/users/qarasiq/folders/Default/media/f3c4d71e-1e9a-4590-92c3-c9bd5676cfe6/ico2.png
* official website: https://exmo.me

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `rgb(52, 127, 251)`

---

---

### Coin name (`QIWI`)

* link to logo: https://ist24.ru/payment/logo_qiwi.png
* official website: https://qiwi.ru

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#FF8C00`

---

---

### Coin name (`SBERBANK`)

* link to logo: https://sberbank.ru/portalserver/content/atom/contentRepository/content?id=8655dfea-3d64-4f01-8bf3-26748db9d36e
* official website: https://sberbank.ru

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#48b254`

---

---

### Coin name (`MUSICOIN`)

* link to logo: https://steemitimages.com/DQmVMspBMbA6gw1bdacR1oA57hTeC7jNqXgp95cTpVGdMxy/musicoin-review.png
* official website: https://musicoin.org/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#fbbf02`

---

---

### Coin name (`SALT`)

* link to logo: http://files.coinmarketcap.com.s3-website-us-east-1.amazonaws.com/static/img/coins/200x200/salt.png
* official website: https://www.saltlending.com/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `rgb(23, 183, 188)`

---

**Comment by cjdowner** [comment]
I've added all the above coins in the latest update. SALT was already included. Thanks for the information!

P.S. Does Sberbank have its own coin/token? That's pretty cool. 🙂
