### ISSUE TITLE
Separating ERC-20 tokens from other coins

### ISSUE THREAD

**Issue by ricburton** [cjdowner/cryptocurrency-icons#60]
I think it would be nice to separate the coins that run on their own chains from the ERC-20 tokens.

I will try and take a pass at it at some point.

**Comment by cjdowner** [comment]
I wonder if this is something that would be possible to note in the manifest rather than having separate folders?

I'm not too familiar with _all_ the coins and tokens in the project so I don't know which ones are ERC exactly.

**Comment by imnotadeveloper** [comment]
I don't see how it would help this project.
The goal is to provide a consistent library of icons, not to classify or to give information about cryptos.

**Comment by ricburton** [comment]
Fair points :)

I just had to go through the icons to weed out the fiat and coin-based tokens. Not a huge issue.

Sent via Superhuman ( https://sprh.mn/?vip=richard@balance.io )
