### ISSUE TITLE
A couple more, all in top 200 marketcap coins

### ISSUE THREAD

**Issue by PSinke** [cjdowner/cryptocurrency-icons#61]
Hi CJDowner,

Thank for adding the last ones I requested. I'm missing a couple more that are traded on Binance. Could you please add these too? 

Bluzelle (BLZ) - https://bluzelle.com/
NANO (NANO) - http://nano.org/			
CyberMiles (CMT) - https://cm.5miles.com/
Nuls (NULS) - https://nuls.io/
SONM (SNM) - https://sonm.io/

Thanks.

**Comment by cjdowner** [comment]
Nano is in the project – https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/color/xrb.png it seems now the `NANO` code has officially changed from `XRB` so I will update accordingly.
Sonm is also in the project. For consistency's sake to CoinMarketCap I will also rename this but provide an alt in the manifest. https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/color/sonm.png

**Comment by PSinke** [comment]
Excellent. Sorry for not catching those myself.

**Comment by aviggiano** [comment]
Thanks, I came here to ask for you if the xrb.png file could be renamed to nano.png

**Comment by cjdowner** [comment]
XRB is now NANO https://github.com/cjdowner/cryptocurrency-icons/commit/d31bf7c3afd479ce9d2adc200a6149cdcbe64835

Hope to have the other coins added soon.

**Comment by cjdowner** [comment]
All added now https://github.com/cjdowner/cryptocurrency-icons/commit/2c5fe1715311c6306e5985025fae78c674abfde7

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
