### ISSUE TITLE
Resize SVGs

### ISSUE THREAD

**Issue by JulioFortunato** [cjdowner/cryptocurrency-icons#63]
Why can't I just resize the svg using `width` or `height`?

**Comment by lunaroyster** [comment]
Not certain, but I think that the `width` and `height` attribs affect only the canvas size, and not the size of the shapes within them.

**Comment by JulioFortunato** [comment]
So, what should be the best way to use the SVGs at any size? 🤔

**Comment by lunaroyster** [comment]
While rendering them. You can render SVGs into regular image formats, perhaps using inkscape. It even works on the command line: https://inkscape.org/sk/doc/inkscape-man.html

If you're embedding svgs into HTML directly, you could simply change the width and height on the svg element: 
![image](https://user-images.githubusercontent.com/6189367/36858933-f35a1106-1da2-11e8-9dad-0e524117967d.png)
