### ISSUE TITLE
confused as to why nano was renamed back to xrb?

### ISSUE THREAD

**Issue by nkaviani** [cjdowner/cryptocurrency-icons#64]
Looks like the ticker name is also changed from `xrb` to `nano`.

I wonder why this commit 349aa584f1c56fab377812875fd622a31e5c8821 changed the icon name to `xrb` even though a crypto with this symbol name does not exist anymore.

From coinmarketcap [HERE](https://api.coinmarketcap.com/v1/ticker/nano/) the `symbol` name is `NANO`.

**Comment by nkaviani** [comment]
Ah I guess it happened after this issue was submitted: https://github.com/cjdowner/cryptocurrency-icons/issues/50

`xrb` is not the symbol anymore. `NANO` seems to be it.

**Comment by cjdowner** [comment]
Fixed https://github.com/cjdowner/cryptocurrency-icons/commit/d31bf7c3afd479ce9d2adc200a6149cdcbe64835

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
