### ISSUE TITLE
Coins Missing from CMC

### ISSUE THREAD

**Issue by altShiftDev** [cjdowner/cryptocurrency-icons#65]
Hey bud,

Me again, I found a bunch of shitcoins near in the CMC (https://coinmarketcap.com/)  top 200 that are either missing or miss-named.

Format: {{ CoinName }} | {{ Symbol }}

    Nano | NANO |  *Coin symbol changed
    MediShares | MDS
    Time New Bank  | TNB
    Theta Token | THETA
    SuperNET | UNITY
    BLOCKv | VEE
    Dynamic Trading Rights | DTR
    Asch | XAS
    Telcoin | TEL
    IoT Chain | ITC
    Bluzelle | BLZ
    DEW | DEW
    SaluS | SLS
    Ink | INK
    SONM | SNM
    QUANTUM RESISTANT LEDGER | QRL
    CRYPTO20 | C20
    DATA | DTA
    BIBOX TOKEN | BIX
    WINGS | WINGS
    NULS | NULS
    EIDOO | EDO
    JIBREL NETWORK | JNT
    AGORAS TOKENS | AGRS
    SPANKCHAIN | SPANK
    ION | ION
    WAGERR | WGR
    WEPOWER | WPR
    COBINHOOD | COB
    XTRABYTES | XBY
    HTMLCOIN | HTML
    CYBERMILES | CMT
    BREAD | BRD
    UTRUST | UTK
 
If I can also make a suggestion - since you're signing up for a nearly endless amount of work with shitcoins coming out daily and dropping in price wildly, keeping up with the cmc 1 - 200 could be a full-time job.... What if you made a fallback icon, so devs could use a generic image if a particular shitcoin doesn't yet have a logo. It would make replacing the icons a lot less urgent if a placeholder was available.

Anyways, thanks for all your hard work, this repo is amazing!

**Comment by cjdowner** [comment]
Just updated the xrb > nano issue. Will need to set aside time to conquer all these.

The idea of a default coin is a great idea indeed. 👍

**Comment by cjdowner** [comment]
Took me a while, but with the exception of C20 and the placeholder, they're done. https://github.com/cjdowner/cryptocurrency-icons/commit/2c5fe1715311c6306e5985025fae78c674abfde7

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
