### ISSUE TITLE
Zencah (Zen) logo changed

### ISSUE THREAD

**Issue by petermumford** [cjdowner/cryptocurrency-icons#66]
Zencash have changed there logo design, which needs updating.

https://zensystem.io/assets/img/icons/zenicon.png

**Comment by cjdowner** [comment]
Updated. Thanks! https://github.com/cjdowner/cryptocurrency-icons/commit/2c5fe1715311c6306e5985025fae78c674abfde7

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
