### ISSUE TITLE
New Icon: Bitcoin Private

### ISSUE THREAD

**Issue by petermumford** [cjdowner/cryptocurrency-icons#67]
Missing icon to add: https://btcprivate.org/presskit/presskit.zip

**Comment by cjdowner** [comment]
Done, thanks! https://github.com/cjdowner/cryptocurrency-icons/commit/2c5fe1715311c6306e5985025fae78c674abfde7

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
