### ISSUE TITLE
LSK changed logo

### ISSUE THREAD

**Issue by tomploem** [cjdowner/cryptocurrency-icons#72]
lisk (LSK) rebranded and created a new logo: 

**github page**
https://github.com/LiskHQ

**github avatar**
https://avatars0.githubusercontent.com/u/16600915?s=200&v=4

**Comment by cjdowner** [comment]
Thanks for letting me know -  https://github.com/cjdowner/cryptocurrency-icons/commit/b1fdfe773734b042c1a0afd942fce985d45ce263

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
