### ISSUE TITLE
Generic icon

### ISSUE THREAD

**Issue by sindresorhus** [cjdowner/cryptocurrency-icons#78]
There are some cryptocurrencies that don't have an icon. Would be nice to have a generic icon here that we could be used in such cases.

**Comment by cjdowner** [comment]
This is a great suggestion, and actually one I added in yesterday's update – https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/color/default.png

I'm not happy with its name though. Do you have any suggestions for better discoverability?

**Comment by lunaroyster** [comment]
As in filename? I think generic.png would work slightly better.

**Comment by cjdowner** [comment]
@fsw I had initially prefixed it with an underscore, but for some reason it wouldn't appear on the compiled cryptoicons.co. `$` works however as seen with `$PAC`.

**Comment by cjdowner** [comment]
I've gone for `generic` for now. Also edited the coin itself a little - https://github.com/cjdowner/cryptocurrency-icons/commit/52c43af520cb4ec7752484509e78a49f844fe2e2

Thanks all!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
