### ISSUE TITLE
SpankChain (SPANK) icon not accurate

### ISSUE THREAD

**Issue by nedsteeg** [cjdowner/cryptocurrency-icons#80]
The exclamation mark is too close to the S.
Fixed version attached
And thanks for your amazing job ;)
[SPANK.svg.zip](https://github.com/cjdowner/cryptocurrency-icons/files/1842055/SPANK.svg.zip)

**Comment by cjdowner** [comment]
Well spotted. Thanks for the SVG, looks better indeed – https://github.com/cjdowner/cryptocurrency-icons/commit/52c43af520cb4ec7752484509e78a49f844fe2e2

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
