### ISSUE TITLE
Missing Icons 25 March

### ISSUE THREAD

**Issue by cjdowner** [cjdowner/cryptocurrency-icons#82]
To add

- [x]  **BRO** Bitradio
- [x]  **SLR** Solarcoin
- [x] **AUTO** Cube
- [x] **CS** Credits
- [x] **BOS** BOScoin
- [x] **ABT** Arcblock
- [x] **FSN** Fusion

Update
- [x] Waltonchain
- [x] Ethereum Classic
- [x] Siacoin
- [x] XPA
- [x] Mediblock

**Comment by Ananthavijay** [comment]
I love to contribute to this issue. could u say me what to do in this issue @cjdowner

**Comment by Serpent6877** [comment]
Please add Ravencoin:
https://bitcointalk.org/index.php?topic=2752467.0

**Comment by Ananthavijay** [comment]
where should I add it ? @Serpent6877

**Comment by Serpent6877** [comment]
@Ananthavijay That was for @cjdowner 

And this would be a 128 color. Also what is the difference between the 128 icon and color files?

**Comment by cjdowner** [comment]
Thanks for your interest @Ananthavijay. To maintain consistency and control, I'm not accepting icon PRs at this time. I'm very happy to add more tokens.

@Serpent6877 will do, thanks! You wouldn't happen to have an SVG of the logo would you?

Each coin will be exported in each style and size. The `color` variant has a solid colour background, whilst `icon` has effects, such as a linear gradient, drop shadows, etc

**Comment by Ananthavijay** [comment]
So @cjdowner  how can I contribute?

**Comment by guptarohit** [comment]
Also, please add XRB to the list. :+1:

**Comment by cjdowner** [comment]
@Serpent6877 added.
@guptarohit XRB as a token, no longer exists https://coinmarketcap.com/search/?q=xrb

**Comment by guptarohit** [comment]
@cjdowner XRB token name is now changed to NANO, but the centre of the [black icon](https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/black/nano.png) is white instead of transparent. Can you please check.
