### ISSUE TITLE
Binance

### ISSUE THREAD

**Issue by Jurikay** [cjdowner/cryptocurrency-icons#85]
Hey, awesome project!
I wanted to quickly ask if you could add [WAN](https://wanchain.org/), [BQX](https://www.ethos.io/) and [CHAT](http://www.openchat.co/). Then we would have an icon for every coin currently listed on Binance. Thanks!

**Comment by Brenndoerfer** [comment]
+1

**Comment by cjdowner** [comment]
Added!

BQX is now Ethos, formerly Bitquence. Coinmarketcap says the token symbol is `ETHOS` so I'm going with that.

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
