### ISSUE TITLE
Improve MONA icon

### ISSUE THREAD

**Issue by jnst** [cjdowner/cryptocurrency-icons#87]
This is a wonderful project! Thank you!!

In the community of the virtual currency, Discord has become mainstream.
However, since the background of `MONA` icon is thin, there is a problem with visibility.
Could you please make the color deeper a more? (`LTC` too.)

Reference: Discord Mac client app. ( `128/icon/mona.png` )
https://i.imgur.com/VzByy5J.png

If you want to try it directly with discord, You can check emoji in this community.
https://discord.gg/ChRDDbz (Invite Link of crypto-emoji)

**Comment by cjdowner** [comment]
I've updated both MONA and Litecoin. It should be better.

It's really great to see the icons as emoji in Discord. Thanks!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
