### ISSUE TITLE
Fill Color for Neo

### ISSUE THREAD

**Issue by altShiftDev** [cjdowner/cryptocurrency-icons#88]
Hi cjdowner,

Since 99% of your icons are so well standardized I've been able to load the svg into the dom, analyze the fill color of the `<circle>` element and use it to set a custom theme color for the coin's page.

So far 99% of the coins I've found work with this method except for Neo. It seems to use a completely different standard (a gradient variable) and the fill color comes back as `url#(a)` instead of a hex code. Is this a mistake unique to neo or is it more common in your files?

![screen shot 2018-04-06 at 5 56 25 pm](https://user-images.githubusercontent.com/24980556/38446138-8630e404-39c4-11e8-990b-27dd3564f353.png)

I've fixed it in my local version of the file but if this is a mistake I'd appreciate it if you could fix the original.

Thanks!

**Comment by cjdowner** [comment]
Updated. Along with `GAS`.

Not sure how the solid colour became a gradient, but it's fixed now. Thanks for noticing!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
