### ISSUE TITLE
Dentacoin colored svg uses mask

### ISSUE THREAD

**Issue by svenlombaert** [cjdowner/cryptocurrency-icons#89]
Hi,

I'm using your svg icons as a resource for a react/react-native project (you may have heard about http://getdelta.io 😉). 

For the react-native version, I need to convert them to a format [react-native-svg](https://github.com/react-native-community/react-native-svg) can work with. Sadly, they don't support masks. I fixed the Dentacoin one so it just uses a regular path. Would be cool if you'd check out my PR!

**EDIT: I also simplified some other that were giving problems.**

Neo and Gas due to using a gradient, sys and nano due to having two fill colors instead of the white parts cut out. It's easier to do color manipulation when there's only one fill color in the svg file.

**Comment by cjdowner** [comment]
Fixed! I wanted to make sure my source file was up-to-date, so I make the changes there just in case I ever needed to re-export those again. Thanks for the PR. 

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
