### ISSUE TITLE
Pls, add karbo

### ISSUE THREAD

**Issue by bonm** [cjdowner/cryptocurrency-icons#9]
Hello, pls, add Karbo icons

Untraceable Exchange Medium
based on CryptoNote blockchain tech.
[http://karbo.io/promo/ ](url)

**Comment by sokyrko** [comment]
+

**Comment by leonardooleg** [comment]
yes, it is very necessary

**Comment by utmcrow** [comment]
+

**Comment by cjdowner** [comment]
Added, closing!

(thank for the link with the vector filetype!)
