### ISSUE TITLE
Nano and Syscoin simplify non-colored version

### ISSUE THREAD

**Issue by svenlombaert** [cjdowner/cryptocurrency-icons#91]
Thanks for addressing the stuff in #89! I have one more request

In my PR (https://github.com/cjdowner/cryptocurrency-icons/pull/90) I fixed two more icons. Both nano.svg and sys.svg (black version) use two fill colors. Because of this, when putting the svg's into the DOM, color manipulation is hard. They're the only two (non color version) icons using two fill colors. It would be nice if they could use one path as well, like the other svgs. Instead of having a `#fff` fill I merged the shapes into one path so we have only one `#000` fill. I opened a new PR to illustrate what I mean: #92 

Also, we'd really like to give back to the community and contribute to this repo. I saw that you closed my last PR, but we'd be willing to add more icons and contribute to this package if you have some guidelines for us.

**Comment by svenlombaert** [comment]
Indeed. I wonder if there's some automated scripts to generate all the different sizes for the png's. The build script outputs to the dist folder, which is in the .gitignore, it would be handy if there was a script to generate the different sizes as well.

**Comment by cjdowner** [comment]
I'll merge these in. Thank you! On my source file, Nano appears as expected, so not sure what's up with that – but there was definitely an issue with the Syscoin icon.

As I mentioned in your other issue, I will create some guidelines for the icons when I return from vacation. This started off really small – I certainly didn't expect it to get so popular and I really appreciate all the support. Ideally I'd like to have all the assets in a source file, though that's not so important. I mainly want to ensure there's consistency and quality among all the icons which is a little trickier!

**Comment by guptarohit** [comment]
Hi @cjdowner, check this black icon of ada [link](https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/black/ada.png), and this black icon of nano [link](https://github.com/cjdowner/cryptocurrency-icons/blob/master/128/black/nano.png). There is white filling in centre of the nano icon, I guess this should be transparent.

**Comment by cjdowner** [comment]
@guptarohit Just updated Nano. https://github.com/cjdowner/cryptocurrency-icons/commit/68877c336de5f5cd69dc46de546edfde5331a148. ADA is definitely contains transparency.

**Comment by guptarohit** [comment]
thanks @cjdowner :)
