### ISSUE TITLE
Add MITH, ELA and CENNZ

### ISSUE THREAD

**Issue by svenlombaert** [cjdowner/cryptocurrency-icons#93]
Hi,

There's three new coins of the top 100 that don't have an icon yet! We went ahead and created the white, black and colored svg already. If you could provide a script/tool/your workflow for creating all the png's, that would be awesome.

Uploaded them to dropbox: https://www.dropbox.com/s/lgme6w16b3zpsph/missing-cryptocurrency-icons.zip?dl=0

**Comment by cjdowner** [comment]
Thanks for including the SVGs - they were very useful.

I create the icons in [Sketch](http://sketchapp.com), where there I export together in the multiple sizes and filetypes. I do plan on creating some documentation at some point.

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
