### ISSUE TITLE
Apex Icon

### ISSUE THREAD

**Issue by TheRealBomber** [cjdowner/cryptocurrency-icons#95]
Hey,

thank you for your reply to my last Issue. The Icons are incredible! 
Another Icon I'm currently missing is the Apex-Icon

Website: https://apex.chinapex.com/
CMC: https://coinmarketcap.com/currencies/apex/

Would love to see what your spin on their icon will be!

Thanks in advance

**Comment by cjdowner** [comment]
Added 😀 

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.

**Comment by TheRealBomber** [comment]
Thank you very much! Looks really good! 
Would you mind changing the filename to the ticker/symbol (CPX) like you did with the other ones?

Much appreciated!
