### ISSUE TITLE
Add Crown (CRW)

### ISSUE THREAD

**Issue by jgleman** [cjdowner/cryptocurrency-icons#96]
Hi, 

Thank you for taking the time to create these icons.

This is to request Crown (CRW) be added:

https://crown.tech
https://coinmarketcap.com/currencies/crown/
https://bittrex.com/Market/Index?MarketName=BTC-CRW

Thanks again for all of your work,
Jason

**Comment by cjdowner** [comment]
Added, thanks Jason!

---
###### Thank you for your support. If you’d like to [tip me](https://github.com/cjdowner/cryptocurrency-icons#donate) for my time in maintaining and updating this project, it would be very much appreciated.
